easy_admin:
    site_name: 'Sama API Admin'
    list:
        title: 'list.%%entity_label%%'
        max_results: 30

    show:
        title: '%%entity_label%% (#%%entity_id%%)'
        max_results: 20

    design:
      brand_color: 'red'
      assets:
        favicon: '/assets/backend/favicon.png'
        css:
          - 'bundles/app/css/admin5.css'
        js:
          - 'bundles/app/js/admin5.js'
    entities:
        # List the entity class name you want to manage
        Article:
            class: App\Entity\Article
            help: 'Veuillez renseigner tous les champs pour editer votre article'
            label: 'Article'

            list:
                title: '%%entity_label%% récent'
                help: 'La liste de tous les articles publiés'
                max_results: 10
                fields:
                  - { property: 'id'}
                  - { property: 'Titre_Article', label: 'Titre' }
                  - { property: 'Image', type: 'image', base_path: '%app.path.article%'}
                  - { property: 'Descriptif', label: 'Description' }
                  - { property: 'Article', label: 'Article' }
                  - { property: 'Date', label: 'Publié le' }
                  - { property: 'Categorie', label: 'Catégorie' }
                  - { property: 'Auteur', label: 'Auteur' }

            show:
                fields:
                - { property: 'Image', label: 'Image', type: 'image', base_path: '%app.path.article%' }
                max_results: 5

            search:
                help: null
                fields: 
                  - { property: 'Titre_Article' }
                  - { property: 'Auteur' }
                  - { property: 'Categorie' }
            form:
                fields:
                  - { property: 'Titre_Article' }
                  - { property: 'imageFile', type: 'file' }
                  - { property: 'Descriptif' }
                  - { property: 'Article'}
                  - { property: 'Date' }
                  - { property: 'Categorie' }
                  - { property: 'Auteur' }
        Competence:
            class: App\Entity\Competence
            help: 'Veuillez renseigner tous les champs pour editer vos competences'
            label: 'Compétence'

            list:
                title: '%%entity_label%% récent'
                help: 'La liste de tous vos competences'
                max_results: 10
                fields:
                  - { property: 'id'}
                  - { property: 'Image', type: 'image', base_path: '%app.path.article%' }
                  - { property: 'Titre'}
            show:
                fields:
                - { property: 'Image', type: 'image', base_path: '%app.path.article%' }
                max_results: 5

            search:
                help: null
                fields: 
                  - { property: 'Titre' }

            form:
                fields:
                  - { property: 'imageFile', type: 'file' }
                  - { property: 'Titre' }

        Perso:
            class: App\Entity\Perso
            help: 'Veuillez renseigner tous les champs pour editer vos informations personnelle'
            label: 'Infos Personnelle'

            list:
                title: '%%entity_label%% récent'
                help: 'La liste de tous vos informations personnelle'
                max_results: 10
                fields:
                  - { property: 'id'}
                  - { property: 'Photo', type: 'image', base_path: '%app.path.perso%' }
                  - { property: 'Prenom'}
                  - { property: 'Nom'}
                  - { property: 'Contact'}
                  - { property: 'Email'}
            show:
                fields:
                - { property: 'Photo', type: 'image', base_path: '%app.path.perso%' }
                max_results: 5

            search:
                help: null
                fields: 
                  - { property: 'Prenom' }
                  - { property: 'Nom' }

            form:
                fields:
                  - { property: 'Prenom' }
                  - { property: 'Nom' }
                  - { property: 'Contact' }
                  - { property: 'Email' }
                  - { property: 'imageFile', type: 'file' }
      
        Projet:
            class: App\Entity\Projet
            
        User:
            class: App\Entity\User
#        - App\Entity\Category
#        - App\Entity\User
